services:
  sqs-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqs-consumer
    restart: unless-stopped
    environment:
      SQS_ENDPOINT: ${SQS_ENDPOINT}
      SQS_QUEUE_URL: ${SQS_QUEUE_URL}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - sqs-network

networks:
  sqs-network:
    driver: bridge
